name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token
      - name: Configure GitHub Token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "CHANGELOG Generator"
          email: "changelog@users.noreply.github.com"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Test lib
        run: |
          npm install
          npm ci
          git checkout master
          npm run test

      - name: Generate CHANGELOG
        run: |
          npm run release
          git push origin master --follow-tags

      - name: NPM Publish
        uses: pascalgn/npm-publish-action@4f4bf159e299f65d21cd1cbd96fc5d53228036df
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^chore(release): (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
